### PR TITLE
Release `eslint-config-nimble` 2.3.0 and `eslint-config-nimble-react` 1.0.0

### PR DESCRIPTION
**Pull request by carryall**
### Chores

- #18 
- #21 
- #22 
- #25 
- #33 

### Features

- #11 
- #13 
- #17 
- #19 

### Bugs

N/A

### CODE REVIEW

**Comment by malparty** [comment]
@carryall I cannot find any commit related to #11, #13, #17, #18, not #21. Is it normal? 🤔

**Comment by hoangmirs** [comment]
> @carryall I cannot find any commit related to #11, #13, #17, #18, not #21. Is it normal? 🤔 

@malparty because they were merged into `master` branch directly before. And then we set `develop` as default branch and worked on that instead

**Comment by carryall** [comment]
That's right @hoangmirs @malparty because we changed the default branch some commits are already merged to `master` 😅

**Review by hoangmirs — APPROVED** [review]

**Review by tyrro — APPROVED** [review]

**Review by malparty — APPROVED** [review]
Then all good :)

**Pull request merged**
